version: '2'
services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - ./docker/.data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: ./docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - 9000:9000
        links:
            - db:mysqldb
            - redis
            - elasticsearch
        volumes:
            - ${BACKEND_PATH}:/var/www/backend
            - ./docker/logs/backend:/var/www/backend/app/logs
    nginx:
        build: ./docker/nginx
        ports:
            # Frontend port
            - 80:80
            # Backend port
            - 81:81
        volumes_from:
            - php
        volumes:
            - ${FRONTEND_PATH}:/var/www/frontend
            - ./docker/logs/nginx/:/var/log/nginx
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
    elasticsearch:
        image: elasticsearch:latest
        working_dir: /data
        command: elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - ./docker/.data/elasticsearch:/data
            - ./docker/.data/elasticsearch:/data/config