#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

#############################################################################
api_login_check:
    path: '/api/login_check'

NelmioApiDocBundle:
    resource: '@NelmioApiDocBundle/Resources/config/routing.yml'
    prefix: '/doc'

app:
    resource: '@AppBundle/Controller/'
    type:     annotation

api:
    resource: '@AppBundle/Controller/Api'
    type:     annotation
    prefix: '/api/v1'
    defaults:
        _format: json

#############################################################################

#remote_browser:
#    resource: "@DownloaderBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#site_manager:
#    resource: "@SiteAnalyzerBundle/Controller/"
#    type:     annotation
#    prefix:   /
