# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username #fos_user.user_provider.username_email - for login by email
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    acl:
        connection: default

    role_hierarchy:
        ROLE_DEFAULT:     ROLE_USER
        ROLE_CLIENT:      ROLE_DEFAULT
        ROLE_SEO:         ROLE_CLIENT
        ROLE_ADMIN:       ROLE_SEO
        ROLE_SUPER_ADMIN: ROLE_ADMIN #[ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  '^/api/login_check'
            stateless: true
            anonymous: true
            form_login:
                check_path:               '/api/login_check'
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   '^/api/'
            stateless: true
            provider: fos_userbundle
            guard:
                authenticators:
                    - app.jwt_token_authenticator #lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: "^/api/login_check$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/api/",       roles: IS_AUTHENTICATED_FULLY }
#        - { path: "^/register", role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: "^/resetting", role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: "^/admin/", role: ROLE_ADMIN }