<?php
declare(strict_types=1);

namespace AppBundle\Security\Guard;

use Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator as BaseAuthenticator;
use Symfony\Component\Security\Core\User\UserProviderInterface;

class JWTTokenAuthenticator extends BaseAuthenticator
{
    public function getUser($preAuthToken, UserProviderInterface $userProvider)
    {
        return parent::getUser($preAuthToken, $userProvider); // TODO: Change the autogenerated stub
    }
}